/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/YWRV02zBfCd
 */
import { Button } from "@/components/ui/button";
import Link from "next/link";

export function Component() {
  return (
    (<div className="bg-white">
      <nav className="flex flex-col items-center justify-center px-8 py-4 bg-white border-b shadow-md">
      <div className="grid grid-cols-2 gap-3 items-center w-full max-w-6xl">
        <div className="flex items-center space-x-4">
          <img alt="Bootcamp Logo" className="h-8" src="/logo.jpeg" />
          <div className="flex space-x-4">
            <Button className="text-sm text-black" variant="ghost">
              Para estudiantes
            </Button>
            <Button className="text-sm text-black" variant="ghost">
              Para empresas
            </Button>
          </div>
        </div>
        <div className="flex items-center space-x-4 justify-self-end">
          <Link className="text-sm text-black" href="#">
            Ingresar
          </Link>
          <Button className="bg-yellow-400 hover:bg-yellow-500" variant="yellow">Aplicar</Button>
          </div>
          </div>
      </nav>
      <div className="flex flex-col items-center justify-center px-8 py-10 bg-white">
        <div className="grid grid-cols-2 gap-3 items-center w-full max-w-6xl">
          <div>
            {/* Adjusting the text container width */}
            <h1 className="text-6xl font-bold mb-4 text-black">
              Comienza o acelera tu carrera en tecnología
            </h1>
            <p className="text-2xl mb-8 text-black  max-w-lg">Estudia Desarrollo Full Stack, Data Science o Data Analytics.</p>
            <ul className="space-y-4 mb-8">
              <li className="flex items-center space-x-2 text-black">
                <CheckCircleIcon className="text-green-500" />
                <span>Online, en vivo y flexible</span>
              </li>
              <li className="flex items-center space-x-2 text-black">
                <CheckCircleIcon className="text-green-500" />
                <span>Basado en proyectos</span>
              </li>
              <li className="flex items-center space-x-2 text-black">
                <CheckCircleIcon className="text-green-500" />
                <span>Basado en cohortes</span>
              </li>
              <li className="flex items-center space-x-2 text-black">
                <CheckCircleIcon className="text-green-500" />
                <span>Garantía de Empleo</span>
              </li>
            </ul>
            <Button className="bg-yellow-400 hover:bg-yellow-500" variant="yellow">Aplicar</Button>
          </div>
          <div>
            <img
              alt="Student at Bootcamp"
              className="rounded-xl"
              src="../placeholder.webp"
              style={{
                aspectRatio: "500/500",
                objectFit: "cover",
              }}
              width="600" />
          </div>
        </div>
      </div>
      <div className="bg-gray-100 py-4 text-center text-black">
        <span className="text-lg font-semibold">Bootcamp #1 de Latam</span>
      </div>
    </div>)
  );
}


function CheckCircleIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14" />
      <polyline points="22 4 12 14.01 9 11.01" />
    </svg>)
  );
}

export default Component;